### ISSUE TITLE
OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by shifenhutu** [fubuloubu/eth-abi#215]
### What happened?

when i  use multicall get some token symbol,  then i try to decode symbol,  a symbol raise a error

### Code that produced the error

```python

import json
import os

from web3 import Web3



ALCHEMY_ETH_MAINNET_KEY = "My key"  # https://www.alchemy.com/


alchemy_https_url = f"https://eth-mainnet.g.alchemy.com/v2/{ALCHEMY_ETH_MAINNET_KEY}"

web3 = Web3(Web3.HTTPProvider(alchemy_https_url))


def getSymbolByAddresses_list(chain, addresses):


    abi_file = os.path.join("../", "abi_files/multicall_abi.json")

    with open(abi_file, 'r') as f:
        multicall_abi = json.load(f)

    multi_address = "0xcA11bde05977b3631167028862bE2a173976CA11"

    multicall_contract = web3.eth.contract(address=multi_address, abi=multicall_abi)
    symbol_calls = [(Web3.to_checksum_address(addr), '0x95d89b41') for addr in addresses]
    res_list_tmp = multicall_contract.functions.tryAggregate(False, symbol_calls).call()
    decode_list = []
    for result in res_list_tmp:

        print("result")
        print(result)

        tmp_symbol = Web3().codec.decode(["string"], result[1])[0]

        print("tmp_symbol", tmp_symbol)


        if result[0] is None or result[0] == False:
            decode_list.append("")
        else:
            decode_list.append(tmp_symbol)

    return decode_list




if __name__ == "__main__":

    empty_symbol_token_list=[ "0xbe042e9d09cb588331ff911c2b46fd833a3e5bd6","0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2"]

    symbol_res = getSymbolByAddresses_list("ethereum", empty_symbol_token_list)
    print("symbol_res: \n", symbol_res)
```

### multicall_abi.json
```
[
  {
    "inputs": [
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "aggregate",
    "outputs": [
      { "internalType": "uint256", "name": "blockNumber", "type": "uint256" },
      { "internalType": "bytes[]", "name": "returnData", "type": "bytes[]" }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bool", "name": "allowFailure", "type": "bool" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call3[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "aggregate3",
    "outputs": [
      {
        "components": [
          { "internalType": "bool", "name": "success", "type": "bool" },
          { "internalType": "bytes", "name": "returnData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Result[]",
        "name": "returnData",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bool", "name": "allowFailure", "type": "bool" },
          { "internalType": "uint256", "name": "value", "type": "uint256" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call3Value[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "aggregate3Value",
    "outputs": [
      {
        "components": [
          { "internalType": "bool", "name": "success", "type": "bool" },
          { "internalType": "bytes", "name": "returnData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Result[]",
        "name": "returnData",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "blockAndAggregate",
    "outputs": [
      { "internalType": "uint256", "name": "blockNumber", "type": "uint256" },
      { "internalType": "bytes32", "name": "blockHash", "type": "bytes32" },
      {
        "components": [
          { "internalType": "bool", "name": "success", "type": "bool" },
          { "internalType": "bytes", "name": "returnData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Result[]",
        "name": "returnData",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getBasefee",
    "outputs": [
      { "internalType": "uint256", "name": "basefee", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }
    ],
    "name": "getBlockHash",
    "outputs": [
      { "internalType": "bytes32", "name": "blockHash", "type": "bytes32" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getBlockNumber",
    "outputs": [
      { "internalType": "uint256", "name": "blockNumber", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getChainId",
    "outputs": [
      { "internalType": "uint256", "name": "chainid", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCurrentBlockCoinbase",
    "outputs": [
      { "internalType": "address", "name": "coinbase", "type": "address" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCurrentBlockDifficulty",
    "outputs": [
      { "internalType": "uint256", "name": "difficulty", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCurrentBlockGasLimit",
    "outputs": [
      { "internalType": "uint256", "name": "gaslimit", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getCurrentBlockTimestamp",
    "outputs": [
      { "internalType": "uint256", "name": "timestamp", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "address", "name": "addr", "type": "address" }
    ],
    "name": "getEthBalance",
    "outputs": [
      { "internalType": "uint256", "name": "balance", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getLastBlockHash",
    "outputs": [
      { "internalType": "bytes32", "name": "blockHash", "type": "bytes32" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "bool", "name": "requireSuccess", "type": "bool" },
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "tryAggregate",
    "outputs": [
      {
        "components": [
          { "internalType": "bool", "name": "success", "type": "bool" },
          { "internalType": "bytes", "name": "returnData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Result[]",
        "name": "returnData",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "bool", "name": "requireSuccess", "type": "bool" },
      {
        "components": [
          { "internalType": "address", "name": "target", "type": "address" },
          { "internalType": "bytes", "name": "callData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Call[]",
        "name": "calls",
        "type": "tuple[]"
      }
    ],
    "name": "tryBlockAndAggregate",
    "outputs": [
      { "internalType": "uint256", "name": "blockNumber", "type": "uint256" },
      { "internalType": "bytes32", "name": "blockHash", "type": "bytes32" },
      {
        "components": [
          { "internalType": "bool", "name": "success", "type": "bool" },
          { "internalType": "bytes", "name": "returnData", "type": "bytes" }
        ],
        "internalType": "struct Multicall3.Result[]",
        "name": "returnData",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  }
]

```

### Full error output

```shell
`
Traceback (most recent call last):
  File "/Users/user11/Documents/GitHub/learn-blockChain/utils/getSymbolMulticall111.py", line 55, in <module>
    symbol_res = getSymbolByAddresses_list("ethereum", empty_symbol_token_list)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user11/Documents/GitHub/learn-blockChain/utils/getSymbolMulticall111.py", line 36, in getSymbolByAddresses_list
    tmp_symbol = Web3().codec.decode(["string"], result[1])[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/codec.py", line 149, in decode
    return decoder(stream)
           ^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 128, in __call__
    return self.decode(stream)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 174, in decode
    yield decoder(stream)
          ^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 128, in __call__
    return self.decode(stream)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 145, in decode
    stream.push_frame(start_pos)
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 95, in push_frame
    self.seek_in_frame(0)
  File "/Users/user11/opt/miniconda3/envs/learn-blockChain/lib/python3.11/site-packages/eth_abi/decoding.py", line 84, in seek_in_frame
    self.seek(self._total_offset + pos, *args, **kwargs)
OverflowError: Python int too large to convert to C ssize_t
`
```

### Fill this section in if you know how this could or should be fixed

replace 

`tmp_symbol = Web3().codec.decode(["string"], result[1])[0]` 

to 

```python
tmp_symbol = Web3.to_text(result[1]).replace("\00", "").replace("\n", "").replace("\t", "").replace("\x02",
                                                                                                                "").replace(
                "\x03", "").replace("\x04", "").replace("\x05", "").replace("\x06", "").replace("\x07", "").replace(
                "\x08", "").replace("\x0b", "").strip()

```

but, this is not a good way

### eth_abi Version

4.1.0

### Python Version

3.11.4

### Operating System

osx

### Output from pip-freeze

```shell
addict==2.4.0
aiohttp==3.8.5
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
bitarray==2.8.0
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
cytoolz==0.12.2
eth-abi==4.1.0
eth-account==0.9.0
eth-hash==0.5.2
eth-keyfile==0.6.1
eth-keys==0.4.0
eth-rlp==0.3.0
eth-typing==3.5.1
eth-utils==2.3.0
frozenlist==1.4.0
hexbytes==0.3.1
idna==3.4
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
lru-dict==1.2.0
many-abis==0.1.8
multidict==6.0.4
parsimonious==0.9.0
protobuf==4.23.4
pycryptodome==3.18.0
python-dotenv==1.0.0
pyunormalize==15.0.0
referencing==0.30.0
regex==2023.6.3
requests==2.31.0
rlp==3.0.0
rpds-py==0.9.2
toolz==0.12.0
typing_extensions==4.7.1
uniswap-python==0.7.1
urllib3==2.0.4
web3==6.11.2
websockets==11.0.3
yarl==1.9.2
```

**Comment by antazoey** [comment]
I am also occasionally running into this error.

**Comment by browolf** [comment]
I have this error trying to decode a large input data 

`decoded_data = decode(types, bytes.fromhex(input_data[2:]))`

you can see the size of the input data on this transaction https://bscscan.com/tx/0xcbf70aa81c21cff3ae91fc95e0ec5b473fbb4d046e898b02cf93830e98fdeb7e

**Comment by dzhalaevd** [comment]
The similar issue already exists here #142

**Comment by browolf** [comment]
> I have this error trying to decode a large input data
> 
> `decoded_data = decode(types, bytes.fromhex(input_data[2:]))`
> 
> you can see the size of the input data on this transaction https://bscscan.com/tx/0xcbf70aa81c21cff3ae91fc95e0ec5b473fbb4d046e898b02cf93830e98fdeb7e

I've had to write my own function to extract the information from the input data - I'm sure it's far from pro code but it works

**Comment by pacrob** [comment]
Closing, same issue as #142
